{% set version = "25.1.0" %}
{% set sha256 = "9934978582cda85c6eaba6b8e7f943926b797e713d5dbb72fbdc2776b7fcae20" %}

package:
  name: galaxy-util
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/galaxy-util/galaxy_util-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - bleach
    - boltons
    - docutils
    - importlib_resources >=5.10.0
    - packaging
    - pyparsing
    - python >={{ python_min }}
    - pyyaml
    - requests
    - routes
    - typing_extensions
    - zipstream-new
    # extras_require:
    #- dictobj
    - future >=1.0.0
    - cheetah3
  run_constrained:
    # Disallow installation of conflicting older package.
    - galaxy-lib <0a0

test:
  requires:
    - python {{ python_min }}
  imports:
    - galaxy
    - galaxy.exceptions
    - galaxy.util
    - galaxy.util.custom_logging
    - galaxy.util.path
    - galaxy.util.template
    - galaxy.util.tool_shed

about:
  home: https://galaxyproject.org
  license: AFL-3.0
  license_file: LICENSE
  summary: Galaxy Generic Utilities
  doc_url: https://docs.galaxyproject.org
  dev_url: https://github.com/galaxyproject/galaxy

extra:
  recipe-maintainers:
    - nsoranzo
    - bgruening
